### PR TITLE
Update Heebo

### PR DESCRIPTION
**Pull request by emmamarichal**
Hi @OdedEzer / @meirsadan 

Here you can find the update of Heebo. I corrected this issue: "Glyph Reversed for U+05F1 HEBREW LIGATURE YIDDISH VAV YOD"; corrected a lot of fails and updated accents.

Please have a look and tell me if it sounds good for you :)
Thank you!

### CODE REVIEW

**Comment by OdedEzer** [comment]
Hi Emma,

I appreciate the update. However, I encountered difficulty locating the
correct link for the updated glyph. Could you please provide a direct link
for my reference?

Thank you,
Oded



- - -
*Prof. Oded Ezer*
Faculty of Design, Holon Institute of Technology

*Oded Ezer Typography* <https://www.odedezer.com/>
<https://www.odedezer.com/>& Team <https://www.odedezer.com/>
Creating Visual Content

*Ezer Type House* <https://www.ezertypehouse.com/>
Independent Type Foundry

*Alliance Graphique Internationale*
<https://a-g-i.org/user/odedezer/view/projects/>
AGI Member

*הקולקטיב* <https://www.hacollective.co.il/>
מגזין לתרבות ועיצוב



‫בתאריך יום ד׳, 4 באוק׳ 2023 ב-17:06 מאת ‪Emma Marichal‬‏ <‪
***@***.***‬‏>:‬

**Comment by emmamarichal** [comment]
Hi @OdedEzer 
here you can find the variable font file: https://github.com/emmamarichal/heebo/blob/master/fonts/variable/Heebo%5Bwght%5D.ttf

And here, the sources (Glyphs file): https://github.com/emmamarichal/heebo/blob/master/sources/Heebo.glyphs

Hope I answered to your question, don't hesitate if you need anything else! :)

**Comment by OdedEzer** [comment]
Hi Emma,
Thank you for providing the links to the variable font file and the sources
(Glyphs file) for Heebo. I appreciate your prompt response.
I'll go through the files and review them. If I have any further questions
or if anything comes up, I'll be sure to reach out to you.
Thanks again for your assistance.
Best regards,
Oded


- - -
*Prof. Oded Ezer*
Faculty of Design, Holon Institute of Technology

*Oded Ezer Typography* <https://www.odedezer.com/>
<https://www.odedezer.com/>& Team <https://www.odedezer.com/>
Creating Visual Content

*Ezer Type House* <https://www.ezertypehouse.com/>
Independent Type Foundry

*Alliance Graphique Internationale*
<https://a-g-i.org/user/odedezer/view/projects/>
AGI Member

*הקולקטיב* <https://www.hacollective.co.il/>
מגזין לתרבות ועיצוב



‫בתאריך יום ו׳, 6 באוק׳ 2023 ב-13:02 מאת ‪Emma Marichal‬‏ <‪
***@***.***‬‏>:‬

**Comment by emmamarichal** [comment]
Hi @OdedEzer,
I also noticed that the ogonek is missing, feel free to add it, this glyphs is required now in the Google Latin Core glyphset :)

Capture d’écran 2023-11-02 à 15 28 20

**Comment by emmamarichal** [comment]
(please, merge my PR before any modifications (kerning and ogonek), to avoid conflicts)

**Comment by OdedEzer** [comment]
Pls send me the last glyphs file you have worked on and I'll correct it
thank you



- - -
*Prof. Oded Ezer*
Faculty of Design, Holon Institute of Technology

*Oded Ezer Typography* <https://www.odedezer.com/>
<https://www.odedezer.com/>& Team <https://www.odedezer.com/>
Creating Visual Content

*Ezer Type House* <https://www.ezertypehouse.com/>
Independent Type Foundry

*Alliance Graphique Internationale*
<https://a-g-i.org/user/odedezer/view/projects/>
AGI Member

*הקולקטיב* <https://www.hacollective.co.il/>
מגזין לתרבות ועיצוב



‫בתאריך יום ה׳, 2 בנוב׳ 2023 ב-16:30 מאת ‪Emma Marichal‬‏ <‪
***@***.***‬‏>:‬

**Comment by emmamarichal** [comment]
sent! thanks !

**Comment by OdedEzer** [comment]
Hi Emma,

I am attaching here the corrected Glyph file for you.
Corrected:
ogonek, ogonekcomb, Aogonek, Eogonek, Iogonek, Uogonek, aogonek, eogonek,
iogonek, uogonek

Corrected:
alefWide-hb

Corrected:
Version 3.003
Creation Date: 04/11/2023
Designer URL: ezertypehouse.com
Manufacturer: Ezer Type House
Manufacturer URL: ezertypehouse.com

Thin Stems:
vStem0: 54
hStem0: 54

shoulderHeight Hebrew: 1157

Regular Stems:
vStem0: 194
hStem0: 156

shoulderHeight Hebrew: 1178

Black Stems:
vStem0: 376
hStem0: 302

shoulderHeight Hebrew: 1210

Best,
Oded





- - -
*Prof. Oded Ezer*
Faculty of Design, Holon Institute of Technology

*Oded Ezer Typography* <https://www.odedezer.com/>
<https://www.odedezer.com/>& Team <https://www.odedezer.com/>
Creating Visual Content

*Ezer Type House* <https://www.ezertypehouse.com/>
Independent Type Foundry

*Alliance Graphique Internationale*
<https://a-g-i.org/user/odedezer/view/projects/>
AGI Member

*הקולקטיב* <https://www.hacollective.co.il/>
מגזין לתרבות ועיצוב



‫בתאריך יום ה׳, 2 בנוב׳ 2023 ב-16:30 מאת ‪Emma Marichal‬‏ <‪
***@***.***‬‏>:‬

**Comment by emmamarichal** [comment]
Hi @OdedEzer!

Thanks a lot for your work. I exported and tested the fonts, it should be ready to onboard :)
I just put back the version 3.000 (we change the version number only when the Google Fonts files are updated)

You can merge this PR!
Thank you,
Cheers!

**Comment by OdedEzer** [comment]
Thank you emmamarichal <https://github.com/emmamarichal>. how do I merge
this PR?



‫בתאריך יום ד׳, 8 בנוב׳ 2023 ב-15:03 מאת ‪Emma Marichal‬‏ <‪
***@***.***‬‏>:‬

**Comment by markhdavid** [comment]
Hello @OdedEzer and @emmamarichal -- THIS MUST NOT GO OUT. I tested the font in Emma's master, and it's not right. The positioning of nikud diacritics under Yiddish digraphs double-vav and double-yod is wrong: they're placed under the second (left-most) subcharacter. Here's a screen shot. Let's NOT regress this, let's fix this. I already sent Emma a corrected version, but I am afraid it got lost in the shuffle. The corrected version of this font is in my repo here: https://github.com/markhdavid/heebo-emma

I realize that there may be other problems or issues with my version, such as missing some latin characters (in a Hebrew font), so I do not think I have the total solution, but it's not right to put out this font to the world with a major regression.

Here is the latest commit in Emma's repo that I'm referencing:
```
commit 707f9bbdd1a18e3fa0f922a460149b52602b8e79 (HEAD -> master, origin/master, origin/HEAD)
Author: Emma Marichal <bonjour@emmamarichal.fr>
Date:   Wed Nov 8 14:01:25 2023 +0100

    font exported + QA (Oded modifications)
```
Here's a screen shot of the following test text: װָאס װֵײן װִי װֶען זײֵ זײַן רײֵן לַײָ
Shown in Font Gauntlet with Heebo Regular (Emma's version):

Yiddish Digraphs Test Text - 2023-11-09 Heebo Regular in Font Gauntlet - Screenshot 2023-11-09 at 12 08 32 PM


Here's a screen shot of the same test text, looking correct, shown in Font Gauntlet with Heebo Regular (Mark's version): 
Yiddish Digraphs Test - Mark David's fixed version - Heebo Regular in Font Gauntlet - Screenshot 2023-11-09 at 12 13 48 PM

Can we please get this right. It's not right to put out a new version of this font with a major regression of these character combinations, especially since one in particular is required for the standard orthography of the Yiddish language (double-yod + patah).

I can explain the problem in one short sentence: the Yiddish digraphs double-yod and double-vav are missing their "bottom" anchor. Here's a picture of how they look (in Emma's version) in Glyphs 3 app:

Double-yod in Glyphs 3 (Emma's version) Screenshot 2023-11-09 at 12 09 56 PM

Double-vav in Glyphs 3 (Emma's version) Screenshot 2023-11-09 at 12 09 41 PM

It's as clear as day: they have no "bottom" anchor.  I hope this helps.  Please let me know if I can test or help further. Thank you.

**Comment by emmamarichal** [comment]
Ok, I blocked the Google PR, no worries. I'll take a look tomorrow :) thanks!

**Pull request merged**
