### PR TITLE
Completion of the [wght].ttf variable font 

### PR DESCRIPTION
**Pull request by pichotta**
@meirsadan
@OdedEzer
The weight axis variable font for **Heebo** is complete. Will you accept this pull request to merge the [wght].ttf and the .ufo sources into the master?

### CODE REVIEW

**Comment by OdedEzer** [comment]
Hi,

There is a missing symbol glyph: newsheqel 20AA glyph

I attach it here for inclusion in the font file.

Thank you,
Oded



- - -
*Oded Ezer Typography *& Team
Tel Aviv / Madrid
a-g-i <https://a-g-i.org/user/odedezer/view/projects/>
odedezer.com <http://www.odedezer.com/>
hebrewtypography.com <http://www.hebrewtypography.com/>




‫בתאריך יום ה׳, 15 באוק׳ 2020 ב-20:36 מאת ‪pichotta‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by meirsadan** [comment]
Hi,
@OdedEzer I've reviewed the binary files and found the sheqel symbol is indeed defined at code point 20AA in the binary font files. Are there any other issues?
@pichotta Can you confirm it exists within your source files? It's been a longstanding bug in the current font offered at the main Google Fonts site
Thanks,
Meir

**Comment by pichotta** [comment]
@meirsadan
@OdedEzer
The /shequel is present both in the source and in the variable font.

Heebo sheqel 2020-10-15 at 3 36 49 PM


Heebo sheqel  2020-10-15 at 3 41 40 PM

**Comment by OdedEzer** [comment]
Happy to hear. I have received numerous requests to correct this problem
since the font was launched.

Meir - do you know of any other issues?

Thanks
Oded



- - -
*Oded Ezer Typography *& Team
Tel Aviv / Madrid
a-g-i <https://a-g-i.org/user/odedezer/view/projects/>
odedezer.com <http://www.odedezer.com/>
hebrewtypography.com <http://www.hebrewtypography.com/>




‫בתאריך יום ה׳, 15 באוק׳ 2020 ב-22:43 מאת ‪pichotta‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by meirsadan** [comment]
No more issues from me, going to merge this request now.
Thanks all

**Comment by OdedEzer** [comment]
Meir - thank you - the old Sheqel symbol looks better than what I have sent
you now. Just saying 😉 <https://emojipedia.org/winking-face/>



- - -
*Oded Ezer Typography *& Team
Tel Aviv / Madrid
a-g-i <https://a-g-i.org/user/odedezer/view/projects/>
odedezer.com <http://www.odedezer.com/>
hebrewtypography.com <http://www.hebrewtypography.com/>




‫בתאריך יום ה׳, 15 באוק׳ 2020 ב-23:42 מאת ‪Meir Sadan‬‏ <‪
notifications@github.com‬‏>:‬

**Pull request merged**
